const {Router}=require('express')
const router=Router()
const auth=require('./middleware/auth')
const pagerouter=require('./router/page')
const settings=require('./router/settings')
const product=require('./router/product')
const faqs=require('./router/faqs')
const attribute=require('./router/attribute')
const category=require('./router/category')
const user=require('./router/user')
const apirouter=require('./router/api')
const sliderrouter=require('./router/slider')

router.use('/admin',pagerouter)
router.use('/api',apirouter)
router.use('/admin/category',category)
router.use('/admin/attribute',attribute)
router.use('/admin/settings',settings)
router.use('/admin/faqs',faqs)
router.use('/admin/product',product)
router.use('/admin/user',user)
router.use('/admin/slider',sliderrouter)

module.exports=router
